#! /bin/sh

bspc config border_width        0
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DP-2 -d 4 5 6
bspc monitor DP-3 -d 1 2 3

bspc rule -a Chromium desktop=^2
bspc rule -a Remmina monitor=DP-2 fullscreen
bspc rule -a nautilus floating

xrandr --output DP-3 --auto --primary
xrandr --output DP-2 --auto --right-of DP-3
feh --bg-scale ~/Pictures/diagonal.jpg &
compton -c &
gnome-settings-daemon &
panel &
