[user]
	name  = Sagar Pandya
	email = sagargp@gmail.com

[core]
	excludesfile = ~/.gitignore_global
	editor       = /usr/bin/vim

[push]
	default = simple

[alias]
  co = checkout
  br = branch
  ci = commit
  st = status
  up = pull
  unstage = reset HEAD --
  last = log -1 HEAD
  lg = log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate
  hi = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
