#!/usr/bin/env python
from optparse import OptionParser
import zipfile
import sys

usage = "usage: %prog [options] compressedfile"
parser = OptionParser(usage=usage)
parser.add_option("-l", "--list", action="store_true", dest="list", help="list files in archive")

(options, args) = parser.parse_args()

if len(args) != 1:
  parser.error("no compressedfile specified")

filename = args[0]

listfiles = None
unextract = None

if filename[-4:] == '.zip':
  listfiles = lambda filename: zipfile.ZipFile(filename, 'r').namelist()
  unextract = lambda filename, destination: zipfile.ZipFile(filename,'r').extractall(path=destination) 
else:
  print 'Unknown filetype'

if options.list:
  print listfiles(filename)
else:
  unextract(filename=filename, destination="/home/rand/Desktop/tmpextract")



# vim:syntax=python
